### PR TITLE
Fix parameter sent to formatFunction

### PR DESCRIPTION
**Pull request by juanruben**

### CODE REVIEW

**Comment by juanruben** [comment]
Hi again

Please let me know if an update in the interface is needed. I think that now that parameter is string.. Didn't notice in my last PR

**Comment by shahabyazdi** [comment]
My suggestion is to accept both object.date & object.format as first & second parameters.
Because in range mode, if the user enable the eachDaysInRange prop, the object.date becomes undefined.(see line 58)

**Comment by juanruben** [comment]
So then I think it would be better to pass the full object. Agree?

**Comment by shahabyazdi** [comment]
Sure 👌

**Pull request merged**
